# <font color=red>NumPy簡介
   
    
-----
● NumPy是因應科學運算而誕生的函示庫，它使用獨特的多維陣列(ndarray)的資料結的資料結構做為運算單位，ndarray可以說是NumPy高速運算的核心。
    
● 也就是說，NumPy是由相同型別(Type)和相同大小(Size)的元素構成的多維容器。ndarray只能儲存具有相同型別的元素，而且各維的元素數量必須是固定。
    
● NumPy的底層是用C或Fortran語言撰寫的，在處理NumPy陣列時，這些運算可以用經過最佳化的NumPy函式來處理。它們會將繁重的工作委託給底層，做到高速運算。

## <font color=red>建立ndarray
    
-----
   


In [1]:
import numpy as np

In [2]:
#建立3組5個位置的陣列 數值為0
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
#建立3組2個位置的陣列 數值為1
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
#建立3~20之間公差為2的等差數列
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
#0~500平分為21分包前包後
np.linspace(0,500,22)

array([  0.        ,  23.80952381,  47.61904762,  71.42857143,
        95.23809524, 119.04761905, 142.85714286, 166.66666667,
       190.47619048, 214.28571429, 238.0952381 , 261.9047619 ,
       285.71428571, 309.52380952, 333.33333333, 357.14285714,
       380.95238095, 404.76190476, 428.57142857, 452.38095238,
       476.19047619, 500.        ])

In [6]:
#直接建立
a=np.array([[3,6,9],[2,4,6]])
a

array([[3, 6, 9],
       [2, 4, 6]])

## <font color=red>陣列物件相關屬性
    
-----
   


In [7]:
#顯示陣列維度
a.ndim

2

In [8]:
#顯示陣列有幾列幾欄
a.shape


(2, 3)

In [9]:
#type: <class 'numpy.ndarray'>
type(a)

numpy.ndarray

In [10]:
#dtype: int32
a.dtype


dtype('int32')

In [11]:
#data: <memory at 0x0000017B40F01BA8>  記憶體位址
a.data

In [12]:
#T 順時針轉90度
a.T

array([[3, 2],
       [6, 4],
       [9, 6]])

In [13]:
#幾個欄位
a.size

6

In [14]:
#itemsize 4
#以byte為單位 顯示每個元素的記憶體使用量
a.itemsize

4

In [15]:
#nbytes 24
##以byte為單位 顯示nbarray所有元素的記憶體使用量
a.nbytes

24

## <font color=red>聚合函式
    
-----
   


In [16]:
#總和
a.sum()

30

In [17]:
#計算乘積
a.prod()

7776

In [18]:
#平均數
a.mean()

5.0

In [19]:
#中位數
np.median(a)

5.0

In [20]:
#最大值
a.max()

9

In [21]:
#最小值
a.min()

2

In [22]:
#查找最大值index
a.argmax()

2

In [23]:
#查找最小值index
a.argmin()

3

In [24]:
#標準差
a.std()

2.309401076758503

In [25]:
#累加
a.cumsum()

array([ 3,  9, 18, 20, 24, 30])

## <font color=red>索引
    
    
-----

In [35]:
x = np.arange(36).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
x[0,3:5]

array([3, 4])

In [38]:
x[4:,4:]

array([[28, 29],
       [34, 35]])

In [39]:
x[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [40]:
x[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

## <font color=red>Slicing 切割
    
    
    
-----

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
slice = arr[5:8]
arr[5:8]=7
arr

array([0, 1, 2, 3, 4, 7, 7, 7, 8, 9])

In [46]:
slice[1]=87
slice

array([ 7, 87,  7])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  7, 87,  7,  8,  9])